heat_template_version: 2014-10-16
description: AutoScaling Infoblox DNS Service
parameters:
  external_network:
    type: string
    description: the network for the public floating IPs (with external GM)
    default: public-138-net
  wapi_url:
    type: string
    description: the URL to access the GM WAPI from the Heat engine
  wapi_username:
    type: string
    description: the username for the WAPI access
  wapi_password:
    type: string
    description: the username for the WAPI access
  wapi_sslverify:
    type: string
    description: the value for SSL Verify (true/false/certificate path)
    default: false
  gm_lan1_ip:
    type: string
    description: the LAN1 IP of the GM, to be used by members for joining the grid
  gm_cert:
    type: string
    description: the GM certificate contents
  min_members:
    type: number
    description: the minimum number of members to keep alive
    default: 2
  max_members:
    type: number
    description: the maximum number of members allowed in the stack
    default: 10
resources:
  nios_member_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: {get_param: min_members}
      max_size: {get_param: max_members}
      resource:
        type: autoscale-member.yaml
        properties:
          gm_lan1_ip: {get_param: gm_lan1_ip}
          external_network: {get_param: external_network}
          parent_stack_id: {get_param: "OS::stack_id"}
  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: nios_member_group}
      cooldown: 900
      scaling_adjustment: 1
  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: nios_member_group}
      cooldown: 900
      scaling_adjustment: -1
  qps_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale up based on QPS
      meter_name: nios.dns.qps
      statistic: avg
      period: 120
      evaluation_periods: 1
      threshold: 100
      alarm_actions:
        - {get_attr: [scaleup_policy, alarm_url]}
      matching_metadata: {'metadata.metering.stack': {get_param: "OS::stack_id"}}
      comparison_operator: gt
  qps_alarm_low:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale down based on QPS
      meter_name: nios.dns.qps
      statistic: avg
      period: 120
      evaluation_periods: 1
      threshold: 10
      alarm_actions:
        - {get_attr: [scaledown_policy, alarm_url]}
      matching_metadata: {'metadata.metering.stack': {get_param: "OS::stack_id"}}
      comparison_operator: lt
